import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/component/common/Header";
import Footer from "@/component/common/Footer";
import Head from "next/head";
import Link from "next/link";
import SocialLinks from "@/component/SocialLinks";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Dr Varun Goel",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Head>
        <Link href="https://fonts.googleapis.com/css2?family=Oswald&display=swap" rel="stylesheet" />
     

      </Head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >

        <Header />
        {children}
        <SocialLinks />
        <Footer />
      </body>
    </html>
  );
}
